---
- name: Ensure the python3-debian package is installed
  ansible.builtin.apt:
    name: python3-debian
    state: present
  check_mode: false

- name: Add GitLab Runner repository
  ansible.builtin.deb822_repository:
    name: gitlab-runner
    types: deb
    uris: "{{ gitlab_runner_repository_url}}"
    suites: "{{ ansible_facts.distribution_release }}"
    components: main
    signed_by: "{{ gitlab_runner_repository_gpg_key_url }}"
  notify:
    - Apt update

- name: Ensure handlers are notified immediately to update the apt cache.
  ansible.builtin.meta: flush_handlers

- name: Install GitLab Runner and GitLab Runner Helper Images
  ansible.builtin.apt:
    name:
      - "gitlab-runner={{ gitlab_runner_version }}"
      - "gitlab-runner-helper-images={{ gitlab_runner_version }}"
    state: present

- name: Ensure GitLab Runner is enabled and started
  ansible.builtin.systemd:
    name: gitlab-runner
    enabled: true
    state: started

- name: Configure GitLab Runner
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/gitlab-runner/config.toml
    owner: root
    group: root
    mode: '0600'
  no_log: "{{ gitlab_runner_no_log }}"

- name: Ensure GitLab Runner user in necessary groups
  ansible.builtin.user:
    name: gitlab-runner
    groups: "{{ gitlab_runner_groups }}"
    append: true
  when: gitlab_runner_groups | length > 0
  notify:
    - Restart GitLab Runner
# tasks file for gitlab_runner
