---
- name: Ensure the python3-debian package is installed
  ansible.builtin.apt:
    name: python3-debian
    state: present
  check_mode: false

- name: Add GitLab Runner repository
  ansible.builtin.deb822_repository:
    name: gitlab-runner
    types: deb
    uris: "{{ gitlab_runner_repository_url}}"
    suites: "{{ ansible_facts.distribution_release }}"
    components: main
    signed_by: "{{ gitlab_runner_repository_gpg_key_url }}"
  notify:
    - Apt update

- name: Ensure handlers are notified immediately to update the apt cache.
  ansible.builtin.meta: flush_handlers

- name: Install GitLab Runner and GitLab Runner Helper Images
  ansible.builtin.apt:
    name:
      - "gitlab-runner={{ gitlab_runner_version }}"
      - "gitlab-runner-helper-images={{ gitlab_runner_version }}"
    state: present

- name: Ensure GitLab Runner is enabled and started
  ansible.builtin.systemd:
    name: gitlab-runner
    enabled: true
    state: started
# tasks file for gitlab_runner
